#!/bin/bash
#SBATCH --job-name=nf_vdj
#SBATCH --ntasks=2
#SBATCH --error=nf_vdj-%j.out
#SBATCH --out=nf_vdj-%j.out
#SBATCH --mem=16G
#SBATCH --partition=dhvi
#SBATCH --ntasks-per-node=2

# Set Nextflow work directory (where process folders and log files are created-- this is different from the output directory)
USERNAME=$(id -un)
export NXF_WORKDIR="/work/${USERNAME}"
export EMAIL="${USERNAME}@duke.edu"

pipeoutdir=/datacommons/dhvi/10X_Genomics_data/Maria_Blasi/NHP197/Group3_NoVax/DH57/Pre/CR7.2/VDJ
mkdir -p "$pipeoutdir"
cd "$pipeoutdir"

nextflow run /hpc/group/dhvi/WieheLab/scripts/nextflow_pipelines/10x-nextflow-pipeline \
--workflow vdj \
--sample_id CX82 \
--species rhesus \
--vdj_raw /datacommons/dhvi/10X_Genomics_data/raw_data/Maria_Blasi/NHP197/20240917_LH00373_0186_A22NLHJLT3 \
--vdj_csv /datacommons/dhvi/10X_Genomics_data/Maria_Blasi/NHP197/Group2_mRNA/CX82/Post/CR7.2/VDJ/CX82_VDJ.csv \
--outdir /datacommons/dhvi/10X_Genomics_data/Maria_Blasi/NHP197/Group2_mRNA/CX82/Post/CR7.2 \
--clonal p \
--cellranger 7.2.0